[package]
name = "cargo-node"
version = "0.1.0"
edition = "2021"
authors = ["Success Kingsley <hello@xosnrdev.com>"]
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils"]
keywords = ["cli", "nodejs", "typescript", "bundling", "linting", "tsup", "biomejs", "rust", "developer-tools"]
license = "MIT"
repository = "https://github.com/xosnrdev/cargo-node"

[dependencies]