[package]
name = "cargo-node"
version = "0.1.0"
edition = "2021"
authors = ["Success Kingsley <hello@xosnrdev.tech>"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]
keywords = [
    "cli",
    "nodejs",
    "bundling",
    "linting",
    "developer-tools",
    "cross-platform",
]
description = "A cross-platform CLI tool designed to streamline your Node.js development workflow."
license = "MIT"
repository = "https://github.com/xosnrdev/cargo-node"

[[bin]]
name = "cargonode"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
fs_extra = "1.3.0"
once_cell = "1.20.2"
serde = { version = "1.0.215", features = ["derive"] }
tempfile = "3.14.0"
tokio = { version = "1.41.1", features = ["macros", "time", "process", "rt-multi-thread"] }
toml = "0.8.19"
ureq = "2.10.1"
walkdir = "2.5.0"
zip-extract = "0.2.1"
