[package]
name = "cargonode"
version = "0.1.0"
edition = "2021"
authors = ["Success Kingsley <hello@xosnrdev.tech>"]
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::build-utils",
]
keywords = ["nodejs-dev-tools", "nodejs-cli-tools", "cross-platform"]
description = """
A CLI tool built with Rust to revolutionize Node.js development workflows.
"""
license = "MIT OR Apache-2.0"
repository = "https://github.com/xosnrdev/cargonode"
build = "build.rs"

[[bin]]
name = "cargonode"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
fs_extra = "1.3.0"
once_cell = "1.20.2"
serde = { version = "1.0.215", features = ["derive"] }
tempfile = "3.14.0"
toml = "0.8.19"
ureq = "2.10.1"
zip-extract = "0.2.1"

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies]
jemallocator = "0.5.4"

[profile.release]
debug = 1

[profile.release-lto]
inherits = "release"
opt-level = 3
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1

# This is the main way to strip binaries in the deb package created by
# 'cargo deb'. For other release binaries, we (currently) call 'strip'
# explicitly in the release process.
[profile.deb]
inherits = "release"
debug = false

[package.metadata.deb]
section = "utils"
assets = [
    [
        "target/release/cargonode",
        "usr/bin/",
        "755",
    ],
    [
        "LICENSE-MIT",
        "usr/share/doc/cargonode/",
        "644",
    ],
    [
        "LICENSE-APACHE",
        "usr/share/doc/cargonode/",
        "644",
    ],
    [
        "CHANGELOG.md",
        "usr/share/doc/cargonode/CHANGELOG",
        "644",
    ],
    [
        "README.md",
        "usr/share/doc/cargonode/README",
        "644",
    ],
]
