[commands.format]
command = ""
args = []
pre_checks = []
env_vars = {}

[commands.check]
command = ""
args = []
pre_checks = []
env_vars = {}

[commands.test]
command = ""
args = []
pre_checks = []
env_vars = {}

[commands.build]
command = ""
args = []
pre_checks = []
env_vars = { "NODE_ENV" = "production" }

[commands.release]
command = ""
args = []
pre_checks = []
env_vars = { "NODE_ENV" = "production" }
